image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - chmod +x gradlew
  - DB_URL=jdbc:mysql://localhost:3306/app DB_USER=app DB_PASS=pass java -jar ./artifacts/app-deadline.jar &

build_script:
  - ./gradlew test --info -Dselenide.headless=true # запускаем тест, флаг --info позволяет выводить больше информации